<?php 

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use App\Country;
use App\Province;
use App\City;

class DataProvinceCitiesTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	
	private function truncate()
	{
		DB::table( 'cities' )->truncate();
		DB::table( 'provinces' )->truncate();
		DB::table( 'countries' )->truncate();
	}

	public function run()
	{
		Model::unguard();
		//$this->truncate();
		$data = [
		    [ 
		    	"name" => "Azuay",
		    	"cities" => [
			        "Abdon Calderon (La Union)",
			        "Amaluza",
			        "Asuncion",
			        "Baños",
			        "Bellavista",
			        "Bulan (Jose Victor Izquierdo)",
			        "Camilo Ponce Enriquez",
			        "Cañaribamba",
			        "Chaucha",
			        "Checa (Jidcay)",
			        "Chican (Guillermo Ortega)",
			        "Chiquintad",
			        "Chordeleg",
			        "Chumblin",
			        "Cochapata",
			        "Cuchil (Cutchil)",
			        "Cuenca",
			        "Cumbe",
			        "Daniel Cordova Toral (El Oriente)",
			        "Dug-Dug",
			        "El Batan",
			        "El Cabo",
			        "El Carmen De Pijili",
			        "El Pan",
			        "El Progreso",
			        "El Sagrario",
			        "El Vecino",
			        "Gil Ramirez Davalos",
			        "Gima",
			        "Giron",
			        "Guachapala",
			        "Gualaceo",
			        "Guarainag",
			        "Guel",
			        "Hermano Miguel",
			        "Huaynacapac",
			        "Jadan",
			        "La Union",
			        "Las Nieves (Chaya)",
			        "Llacao",
			        "Ludo",
			        "Luis Cordero Vega",
			        "Luis Galarza Orellana",
			        "Machangara",
			        "Mariano Moreno",
			        "Molleturo",
			        "Monay",
			        "Nabon",
			        "Nulti",
			        "Octavio Cordero Palacios (Santa Rosa)",
			        "Paccha",
			        "Palmas",
			        "Paute",
			        "Principal",
			        "Pucara",
			        "Quingeo",
			        "Remigio Crespo Toral (Gulag)",
			        "Ricaurte",
			        "San Bartolome",
			        "San Blas",
			        "San Cristobal (Carlos Ordoñez Lazo)",
			        "San Felipe De Oña",
			        "San Fernando",
			        "San Gerardo",
			        "San Joaquin",
			        "San Jose De Raranga",
			        "San Juan",
			        "San Martin De Puzhio",
			        "San Rafael De Sharug",
			        "San Sebastian",
			        "San Vicente",
			        "Santa Ana",
			        "Santa Isabel (Chaguarurco)",
			        "Sayausi",
			        "Sevilla De Oro",
			        "Sidcay",
			        "Sigsig",
			        "Sinincay",
			        "Sucre",
			        "Susudel",
			        "Tarqui",
			        "Tomebamba",
			        "Totoracocha",
			        "Turi",
			        "Valle",
			        "Victoria Del Portete (Irquis)",
			        "Yanuncay",
			        "Zhaglli (Shaglli)",
			        "Zhidmad"
			    ],
			],
		    [ 
		    	"name" => "Bolivar",
		    	"cities" => [
		        "Angel Polibio Chavez",
		        "Asuncion (Asancoto)",
		        "Balsapamba",
		        "Bilovan",
		        "Caluma",
		        "Chillanes",
		        "Echeandia",
		        "Facundo Vela",
		        "Gabriel Ignacio Veintimilla",
		        "Guanujo",
		        "Guaranda",
		        "Julio E. Moreno (Catahuan Grande)",
		        "Las Mercedes",
		        "Las Naves",
		        "Magdalena (Chapacoto)",
		        "Regulo De Mora",
		        "Salinas",
		        "San Jose De Chimbo",
		        "San Jose Del Tambo (Tambopamba)",
		        "San Lorenzo",
		        "San Luis De Pambil",
		        "San Miguel",
		        "San Pablo (San Pablo De Atenas)",
		        "San Sebastian",
		        "San Simon (Yacoto)",
		        "San Vicente",
		        "Santafe (Santa Fe)",
		        "Santiago",
		        "Simiatug",
		        "Telimbela"
			    ],
			],
		    [ 
		    	"name" => "Cañar",
		    	"cities" => [
		        "Aurelio Bayas Martinez",
		        "Azogues",
		        "Azogues",
		        "Biblian",
		        "Borrero",
		        "Cañar",
		        "Chontamarca",
		        "Chorocopte",
		        "Cojitambo",
		        "Deleg",
		        "Ducur",
		        "El Tambo",
		        "General Morales (Socarte)",
		        "Gualleturo",
		        "Guapan",
		        "Honorato Vasquez (Tambo Viejo)",
		        "Ingapirca",
		        "Javier Loyola (Chuquipata)",
		        "Jerusalen",
		        "Juncal",
		        "La Troncal",
		        "Luis Cordero",
		        "Manuel J. Calle",
		        "Nazon",
		        "Pancho Negro",
		        "Pindilig",
		        "Rivera",
		        "San Antonio",
		        "San Francisco",
		        "San Francisco De Sageo",
		        "San Miguel",
		        "Solano",
		        "Suscal",
		        "Taday",
		        "Turupamba",
		        "Ventura",
		        "Zhud"
			    ],
			],
		    [ 
		    	"name" => "Carchi",
		    	"cities" => [
		        "27 De Septiembre",
		        "Bolivar",
		        "Chitan De Navarrete",
		        "Concepcion",
		        "Cristobal Colon",
		        "El Angel",
		        "El Angel",
		        "El Carmelo (El Pun)",
		        "El Chical",
		        "El Goaltal",
		        "Fernandez Salvador",
		        "Garcia Moreno",
		        "Gonzales Suarez",
		        "Gonzalez Suarez",
		        "Huaca",
		        "Jijon Y Caamaño",
		        "Juan Montalvo",
		        "Julio Andrade (Orejuela)",
		        "La Libertad (Alizo)",
		        "La Paz",
		        "Los Andes",
		        "Maldonado",
		        "Mariscal Sucre",
		        "Mira (Chontahuasi)",
		        "Monte Olivo",
		        "Piartal",
		        "Pioter",
		        "San Gabriel",
		        "San Isidro",
		        "San Jose",
		        "San Rafael",
		        "San Vicente De Pusir",
		        "Santa Martha De Cuba",
		        "Tobar Donoso (La Bocana De Camumbi)",
		        "Tufiño",
		        "Tulcan",
		        "Tulcan",
		        "Urbina (Taya)"
			    ],
			],
		    [ 
		    	"name" => "Cotopaxi",
		    	"cities" => [
		        "11 De Noviembre (Ilinchisi)",
		        "Alaques (Alaquez)",
		        "Angamarca",
		        "Antonio Jose Holguin (Santa Lucia)",
		        "Belisario Quevedo (Guanailin)",
		        "Canchagua",
		        "Chantilin",
		        "Chugchilan",
		        "Cochapamba",
		        "Cusubamba",
		        "El Carmen",
		        "El Corazon",
		        "Eloy Alfaro (San Felipe)",
		        "Guaitacama (Guaytacama)",
		        "Guangaje",
		        "Guasaganda",
		        "Ignacio Flores (Parque Flores)",
		        "Isinlivi",
		        "Joseguango Bajo",
		        "Juan Montalvo (San Sebastian)",
		        "La Mana",
		        "La Matriz",
		        "La Victoria",
		        "Las Pampas",
		        "Latacunga",
		        "Moraspungo",
		        "Mulalillo",
		        "Mulalo",
		        "Mulliquindil (Santa Ana)",
		        "Palo Quemado",
		        "Pansaleo",
		        "Pilalo",
		        "Pinllopata",
		        "Poalo",
		        "Pucayacu",
		        "Pujili",
		        "Ramon Campaña",
		        "San Buenaventura",
		        "San Juan De Pastocalle",
		        "San Miguel",
		        "Saquisili",
		        "Sigchos",
		        "Tanicuchi",
		        "Tingo",
		        "Toacaso",
		        "Zumbahua"
			    ],
			],
		    [ 
		    	"name" => "Chimborazo",
		    	"cities" => [
		        "Achupallas",
		        "Alausi",
		        "Bilbao",
		        "Cacha",
		        "Cajabamba",
		        "Calpi",
		        "Capzol",
		        "Cañi",
		        "Cebadas",
		        "Chambo",
		        "Chunchi",
		        "Columbe",
		        "Compud",
		        "Cubijies",
		        "Cumanda",
		        "El Altar",
		        "El Rosario",
		        "Flores",
		        "Gonzol",
		        "Guamote",
		        "Guanando",
		        "Guano",
		        "Guasuntos",
		        "Huigra",
		        "Ilapo",
		        "Juan De Velasco (Pangor)",
		        "La Candelaria",
		        "La Matriz",
		        "La Providencia",
		        "Lican",
		        "Licto",
		        "Lizarzaburu",
		        "Llagos",
		        "Maldonado",
		        "Matus",
		        "Multitud",
		        "Pallatanga",
		        "Palmira",
		        "Penipe",
		        "Pistishi (Nariz Del Diablo)",
		        "Puela",
		        "Pumallacta (Puma-Lacta)",
		        "Pungala",
		        "Punin",
		        "Quimiag",
		        "Riobamba",
		        "San Andres",
		        "San Antonio De Bayushig",
		        "San Gerardo De Pacaicaguan",
		        "San Isidro De Patulu",
		        "San Jose Del Chazo",
		        "San Juan",
		        "San Luis",
		        "Santa Fe De Galan",
		        "Santiago De Quito",
		        "Sevilla",
		        "Sibambe",
		        "Sicalpa",
		        "Tixan",
		        "Valparaiso",
		        "Velasco",
		        "Veloz",
		        "Villa La Union (Cajabamba)",
		        "Yaruquies"
		    	],
		    ],
		    [ 
		    	"name" => "El Oro",
		    	"cities" => [
		        "Abañin",
		        "Arcapamba",
		        "Arenillas",
		        "Ayapamba",
		        "Balsas",
		        "Barbones (Sucre)",
		        "Bellamaria",
		        "Bellamaria",
		        "Bellavista",
		        "Bolivar",
		        "Buenavista",
		        "Capiro",
		        "Carcabon",
		        "Casacay",
		        "Cañaquemada",
		        "Chacras",
		        "Chilla",
		        "Cordoncillo",
		        "Curtincapa",
		        "Ecuador",
		        "El Cambio",
		        "El Guabo",
		        "El Ingenio",
		        "El Paraiso",
		        "El Paraiso",
		        "El Retiro",
		        "Guanazan",
		        "Guizhaguiña",
		        "Hualtaco",
		        "Huaquillas",
		        "Huertas",
		        "Jambeli",
		        "Jeli",
		        "La Avanzada",
		        "La Bocana",
		        "La Iberia",
		        "La Libertad",
		        "La Matriz",
		        "La Peaña",
		        "La Providencia",
		        "La Susaya",
		        "La Victoria",
		        "Loma De Franco",
		        "Machala",
		        "Machala",
		        "Malvas",
		        "Marcabeli",
		        "Milagro",
		        "Milton Reyes",
		        "Morales",
		        "Moromoro (Cab. En El Vado)",
		        "Muluncay Grande",
		        "Nueve De Mayo",
		        "Ochoa Leon (Matriz)",
		        "Paccha",
		        "Palmales",
		        "Pasaje",
		        "Piedras",
		        "Piñas",
		        "Piñas Grande",
		        "Portovelo",
		        "Progreso",
		        "Puerto Bolivar",
		        "Salati",
		        "Salvias",
		        "San Antonio",
		        "San Isidro",
		        "San Jose",
		        "San Roque (Ambrosio Maldonado)",
		        "Santa Rosa",
		        "Santa Rosa",
		        "Saracay",
		        "Sinsao",
		        "Tendales (Cab. En Puerto)",
		        "Torata",
		        "Tres Cerritos",
		        "Union Lojana",
		        "Uzhcurrumi",
		        "Victoria",
		        "Zaruma"
			    ],
			],
		    [ 
		    	"name" => "Esmeraldas",
		    	"cities" => [
		        "5 De Agosto",
		        "5 De Junio",
		        "Alto Tambo",
		        "Anchayacu",
		        "Ancon (Pichangal)",
		        "Atacames",
		        "Atahualpa",
		        "Bartolome Ruiz (Cesar Franco Carrion)",
		        "Bolivar",
		        "Borbon",
		        "Calderon",
		        "Camarones",
		        "Carondelet",
		        "Chinca",
		        "Chontaduro",
		        "Chumunde",
		        "Chura (Chancama)",
		        "Colon Eloy Del Maria",
		        "Concepcion",
		        "Crnel. Carlos Ochoa Torres",
		        "Cube",
		        "Daule",
		        "Esmeraldas",
		        "Esmeraldas",
		        "Galera",
		        "La Tola",
		        "La Union",
		        "La Union",
		        "Lagarto",
		        "Luis Tello (Las Palmas)",
		        "Luis Vargas Torres",
		        "Majua",
		        "Maldonado",
		        "Malimpia",
		        "Mataje",
		        "Montalvo",
		        "Muisne",
		        "Pampanal De Bolivar",
		        "Quingue (Olmedo Perdomo Franco)",
		        "Rioverde",
		        "Rocafuerte",
		        "Rosa Zarate (Quininde)",
		        "Salima",
		        "San Francisco",
		        "San Francisco De Onzole",
		        "San Gregorio",
		        "San Javier De Cachavi",
		        "San Jose De Cayapas",
		        "San Jose De Chamanga",
		        "San Lorenzo",
		        "San Mateo",
		        "Santa Rita",
		        "Santo Domingo De Onzole",
		        "Selva Alegre",
		        "Sua",
		        "Tabiazo",
		        "Tachina",
		        "Tambillo",
		        "Telembi",
		        "Timbire",
		        "Tonchigue",
		        "Tonsupa",
		        "Tulubi",
		        "Urbina",
		        "Valdez (Limones)",
		        "Viche",
		        "Vuelta Larga"
			    ],
			],
		    [ 
		    	"name" => "Guayas",
		    	"cities" => [
		        "Alfredo Baquerizo Moreno",
		        "Anconcito",
		        "Atahualpa",
		        "Ayacucho",
		        "Balao",
		        "Ballenita",
		        "Balzar",
		        "Bocana",
		        "Bolivar (Sagrario)",
		        "Candilejos",
		        "Carbo (Concepcion)",
		        "Carlos Espinoza Larrea",
		        "Central",
		        "Chaundy",
		        "Chobo",
		        "Chongon",
		        "Colimes",
		        "Colonche",
		        "Coronel Marcelino Maridueña",
		        "Crnel. Lorenzo De Garaicoa (Pedregal)",
		        "Daule",
		        "El Rosario",
		        "El Salitre (Las Ramas)",
		        "El Triunfo",
		        "Eloy Alfaro (Duran)",
		        "Febres Cordero",
		        "Garcia Moreno",
		        "General Antonio Elizalde (Bucay)",
		        "General Vernaza (Dos Esteros)",
		        "General Villamil",
		        "Gral Alberto Gallo",
		        "Gral. Pedro J. Montero (Boliche)",
		        "Guayaquil",
		        "Guayas (Pueblo Nuevo)",
		        "Isidro Ayora",
		        "Jesus Maria",
		        "Jose Luis Tamayo (Muey)",
		        "Juan Bautista Aguirre (Los Tintos)",
		        "Juan Gomez Rendon (Progreso)",
		        "Junquillal",
		        "La Libertad",
		        "La Victoria (Ñauza)",
		        "Las Lojas (Enrique Baquerizo Moreno)",
		        "Laurel",
		        "Letamendi",
		        "Limonal",
		        "Lomas De Sargentillo",
		        "Manglaralto",
		        "Mariscal Sucre (Huaques)",
		        "Milagro",
		        "Morro",
		        "Naranjal",
		        "Naranjito",
		        "Narcisa De Jesus",
		        "Nueve De Octubre",
		        "Olmedo (San Alejo)",
		        "Palestina",
		        "Paraiso",
		        "Pascuales",
		        "Pedro Carbo",
		        "Posorja",
		        "Puna",
		        "Roberto Astudillo",
		        "Roca",
		        "Rocafuerte",
		        "Sabanilla",
		        "Salinas",
		        "Samborondon",
		        "San Carlos",
		        "San Jacinto De Yaguachi",
		        "San Mateo",
		        "Santa Elena",
		        "Santa Elena",
		        "Santa Lucia",
		        "Santa Rosa De Flandes",
		        "Simon Bolivar",
		        "Simon Bolivar (Julio Moreno)",
		        "Sucre",
		        "Tarifa",
		        "Tarqui",
		        "Taura",
		        "Tenguel",
		        "Urdaneta",
		        "Valle De La Virgen",
		        "Velasco Ibarra (El Empalme)",
		        "Vicente Rocafuerte",
		        "Virgen De Fatima",
		        "Ximena",
		        "Yaguachi Viejo (Cone)"
			    ],
			],
		    [ 
		    	"name" => "Imbabura",
		    	"cities" => [
		        "6 De Julio De Cuellaje",
		        "Ambuqui",
		        "Andrade Marin (Lourdes)",
		        "Angochagua",
		        "Apuela",
		        "Atuntaqui",
		        "Atuntaqui",
		        "Cahuasqui",
		        "Caranqui",
		        "Carolina",
		        "Chuga",
		        "Cotacachi",
		        "Dr. Miguel Egas Cabezas (Peguche)",
		        "Eugenio Espejo (Calpaqui)",
		        "Garcia Moreno (Llurimagua)",
		        "Gonzalez Suarez",
		        "Guayaquil De Alpachaca",
		        "Ibarra",
		        "Imantag",
		        "Imbaya (San Luis De Cobuendo)",
		        "Jordan",
		        "La Dolorosa Del Piorato",
		        "La Esperanza",
		        "La Merced De Buenos Aires",
		        "Lita",
		        "Mariano Acosta",
		        "Otavalo",
		        "Pablo Arenas",
		        "Pataqui",
		        "Peñaherrera",
		        "Pimampiro",
		        "Plaza Gutierrez (Calvario)",
		        "Quiroga",
		        "Sagrario",
		        "Sagrario",
		        "Salinas",
		        "San Antonio",
		        "San Blas",
		        "San Francisco",
		        "San Francisco",
		        "San Francisco De Natabuel",
		        "San Francisco De Sigsipam",
		        "San Jose De Chaltura",
		        "San Jose De Quichinche",
		        "San Juan De Iluman",
		        "San Luis",
		        "San Pablo",
		        "San Rafael",
		        "San Roque",
		        "Selva Alegre",
		        "Tumbabiro",
		        "Urcuqui",
		        "Vacas Galindo (El Churo)"
			    ],
			],
		    [ 
		    	"name" => "Loja",
		    	"cities" => [
		        "12 De Diciembre",
		        "27 De Abril",
		        "Alamor",
		        "Amaluza",
		        "Amarillos",
		        "Bellavista",
		        "Buenavista",
		        "Cangonama",
		        "Cariamanga",
		        "Cariamanga",
		        "Casanga",
		        "Catacocha",
		        "Catacocha",
		        "Catamayo",
		        "Catamayo (La Toma)",
		        "Cazaderos",
		        "Celica",
		        "Chaguarpamba",
		        "Changaimina (La Libertad)",
		        "Chantaco",
		        "Chaquinal",
		        "Chile",
		        "Chuquiribamba",
		        "Ciano",
		        "Colaisaca",
		        "Cruzpamba",
		        "El Airo",
		        "El Arenal",
		        "El Cisne",
		        "El Ingenio",
		        "El Limo (Mariana De Jesus)",
		        "El Lucero",
		        "El Paraiso De Celen",
		        "El Rosario",
		        "El Sagrario",
		        "El Tablon",
		        "El Tambo",
		        "Fundochamba",
		        "Garzareal",
		        "General Eloy Alfaro (San Sebastian)",
		        "Gonzanama",
		        "Guachanama",
		        "Gualel",
		        "Guayquichuma",
		        "Jimbilla",
		        "Jimbura",
		        "La Victoria",
		        "Larama",
		        "Lauro Guerrero",
		        "Limones",
		        "Lluzhapa",
		        "Loja",
		        "Lourdes",
		        "Macara",
		        "Macara (Manuel Enrique Rangel Suquilanda)",
		        "Malacatos (Valladolid)",
		        "Manu",
		        "Mercadillo",
		        "Nambacola",
		        "Nueva Fatima",
		        "Olmedo",
		        "Orianga",
		        "Paletillas",
		        "Pindal",
		        "Pozul (San Juan De Pozul)",
		        "Purunuma (Eguiguren)",
		        "Quilanga",
		        "Quinara",
		        "Sabanilla",
		        "Sabiango (La Capilla)",
		        "Sacapalca",
		        "San Antonio",
		        "San Antonio De Las Aradas",
		        "San Antonio De Quimbe (Cumbe)",
		        "San Jose",
		        "San Lucas",
		        "San Pablo De Tenta",
		        "San Pedro De La Bendita",
		        "San Pedro De Vilcabamba",
		        "San Sebastian",
		        "San Sebastian De Yuluc",
		        "San Vicente",
		        "Sangillin",
		        "Santa Rufina",
		        "Santa Teresita",
		        "Santiago",
		        "Saraguro",
		        "Selva Alegre",
		        "Sozoranga",
		        "Sucre",
		        "Tacamoros",
		        "Taquil (Miguel Riofrio)",
		        "Tingue",
		        "Tnte. Maximiliano Rodriguez Loayza",
		        "Urdaneta (Paquishapa)",
		        "Utuana",
		        "Valle",
		        "Vicentino",
		        "Vilcabamba (Victoria)",
		        "Yamana",
		        "Yangana (Arsenio Castillo)",
		        "Zambi",
		        "Zapotillo"
		    	],
		    ],
		    [ 
		    	"name" => "Los Rios",
		    	"cities" => [
		        "24 De Mayo",
		        "Antonio Sotomayor",
		        "Baba",
		        "Babahoyo",
		        "Barreiro",
		        "Caracol",
		        "Catarama",
		        "Clemente Baquerizo",
		        "Dr. Camilo Ponce",
		        "El Salto",
		        "Febres Cordero",
		        "Guare",
		        "Guayacan",
		        "Isla De Bejucal",
		        "La Union",
		        "Las Esperanza",
		        "Mocache",
		        "Montalvo",
		        "Nicolas Infante Diaz",
		        "Palenque",
		        "Patricia Pilar",
		        "Pimocha",
		        "Puebloviejo",
		        "Puerto Pechiche",
		        "Quevedo",
		        "Quevedo",
		        "Quinsaloma",
		        "Ricaurte",
		        "San Camilo",
		        "San Carlos",
		        "San Cristobal",
		        "San Jacinto De Buena Fe",
		        "San Juan",
		        "Siete De Octubre",
		        "Valencia",
		        "Ventanas",
		        "Venus Del Rio Quevedo",
		        "Vinces",
		        "Viva Alfaro",
		        "Zapotal"
			    ],
			],
		    [ 
		    	"name" => "Manabí",
		    	"cities" =>[
		        "10 De Agosto",
		        "12 De Marzo",
		        "4 De Diciembre",
		        "Abdon Calderon (San Francisco)",
		        "Alhajuela (Bajo Grande)",
		        "America",
		        "Andres De Vera",
		        "Angel Pedro Giler",
		        "Anibal San Andres",
		        "Arq. Sixto Duran Ballen",
		        "Atahualpa",
		        "Ayacucho",
		        "Bachillero",
		        "Bahia De Caraquez",
		        "Bahia De Caraquez",
		        "Barraganete",
		        "Bellavista",
		        "Boyaca",
		        "Calceta",
		        "Campozano (La Palma De Pajan)",
		        "Canoa",
		        "Canuto",
		        "Cascol",
		        "Charapoto",
		        "Chibunga",
		        "Chirijos",
		        "Chone",
		        "Chone",
		        "Cojimies",
		        "Colon",
		        "Convento",
		        "Crucita",
		        "Dr. Miguel Moran Lucio",
		        "El Anegado",
		        "El Carmen",
		        "El Carmen",
		        "Eloy Alfaro",
		        "Eloy Alfaro",
		        "Flavio Alfaro",
		        "Guale",
		        "Honorato Vasquez",
		        "Jama",
		        "Jaramijo",
		        "Jipijapa",
		        "Julcuy",
		        "Junin",
		        "La Pila",
		        "La Union",
		        "La Union",
		        "Lascano",
		        "Leonidas Plaza Gutierrez",
		        "Lodana",
		        "Los Esteros",
		        "Machalilla",
		        "Manta",
		        "Manta",
		        "Manuel Inocencio Parrales Y Guale",
		        "Membrillal",
		        "Membrillo",
		        "Montecristi",
		        "Montecristi",
		        "Noboa",
		        "Olmedo",
		        "Pajan",
		        "Pedernales",
		        "Pedro Pablo Gomez",
		        "Pichincha",
		        "Picoaza",
		        "Portoviejo",
		        "Portoviejo",
		        "Pueblo Nuevo",
		        "Puerto De Cayo",
		        "Puerto Lopez",
		        "Quiroga",
		        "Ricaurte",
		        "Riochico (Rio Chico)",
		        "Rocafuerte",
		        "Salango",
		        "San Antonio",
		        "San Francisco De Novillo",
		        "San Isidro",
		        "San Lorenzo",
		        "San Lorenzo De Jipijapa",
		        "San Mateo",
		        "San Pablo",
		        "San Pablo",
		        "San Pedro De Suma",
		        "San Placido",
		        "San Sebastian",
		        "San Vicente",
		        "Santa Ana",
		        "Santa Ana De Vuelta Larga",
		        "Santa Marianita (Boca De Pacoche)",
		        "Santa Rita",
		        "Sucre",
		        "Tarqui",
		        "Tosagua",
		        "Wilfrido Loor Moreira (Maicito)",
		        "Zapallo"
		    	],
		    ],
		    [ 
		    	"name" => "Morona Santiago",
		    	"cities" => [
		        "Ahuano",
		        "Archidona",
		        "Baeza",
		        "Carlos Julio Arosemena T.",
		        "Chontapunta",
		        "Cosanga",
		        "Cotundo",
		        "Cuyuja",
		        "El Chaco",
		        "Gonzalo Diaz De Pineda (El Bombon)",
		        "Linares",
		        "Oyacachi",
		        "Pano",
		        "Papallacta",
		        "Puerto Misahualli",
		        "Puerto Napo",
		        "San Francisco De Borja (Virgilio Davila)",
		        "San Jose De Payamino",
		        "San Pablo De Ushpayacu",
		        "Santa Rosa",
		        "Sardinas",
		        "Sumaco",
		        "Talag",
		        "Tena"
			    ],
			],
		    [ 
		    	"name" => "Pastaza",
		    	"cities" => [
		        "Arajuno",
		        "Canelos",
		        "Curaray",
		        "Diez De Agosto",
		        "El Triunfo",
		        "Fatima",
		        "Madre Tierra",
		        "Mera",
		        "Montalvo (Andoas)",
		        "Pomona",
		        "Puyo",
		        "Rio Corrientes",
		        "Rio Tigre",
		        "Santa Clara",
		        "Sarayacu",
		        "Shell",
		        "Simon Bolivar",
		        "Tarqui",
		        "Teniente Hugo Ortiz",
		        "Veracruz (Indillama)"
			    ],
			],
		    [ 
		    	"name" => "Pichincha",
		    	"cities" => [
			        "Abraham Calazacon",
			        "Alangasi",
			        "Alfaro (Chimbacalle)",
			        "Alluriquin",
			        "Aloag",
			        "Aloasi",
			        "Amaguaña",
			        "Ascazubi",
			        "Atahualpa (Habaspamba)",
			        "Ayora",
			        "Benalcazar",
			        "Bomboli",
			        "Calacali",
			        "Calderon (Carapungo)",
			        "Cangahua",
			        "Carcelen",
			        "Cayambe",
			        "Cayambe",
			        "Chaupicruz (La Concepcion)",
			        "Chavezpamba",
			        "Checa (Chilpa)",
			        "Chillogallo",
			        "Chimbacalle",
			        "Chinguilpe",
			        "Conocoto",
			        "Cotocollao",
			        "Cotogchoa",
			        "Cumbaya",
			        "Cutuglahua",
			        "El Batan",
			        "El Beaterio",
			        "El Chaupi",
			        "El Inca",
			        "El Quinche",
			        "El Salvador",
			        "Eloy Alfaro",
			        "Gonzalez Suarez",
			        "Gualea",
			        "Guamani",
			        "Guangopolo",
			        "Guapulo",
			        "Guayllabamba",
			        "Juan Montalvo",
			        "La Concepcion",
			        "La Esperanza",
			        "La Floresta",
			        "La Libertad",
			        "La Magdalena",
			        "La Merced",
			        "La Vicentina",
			        "Las Cuadras",
			        "Llano Chico",
			        "Lloa",
			        "Luz De America",
			        "Machachi",
			        "Malchingui",
			        "Manuel Cornejo Astorga (Tandapi)",
			        "Mindo",
			        "Nanegal",
			        "Nanegalito",
			        "Nayon",
			        "Nono",
			        "Olmedo (Pesillo)",
			        "Oton",
			        "Pacto",
			        "Pedro Vicente Maldonado",
			        "Perucho",
			        "Pifo",
			        "Pintag",
			        "Pomasqui",
			        "Puellaro",
			        "Puembo",
			        "Puerto Limon",
			        "Puerto Quito",
			        "Quito",
			        "Rio Toachi",
			        "Rio Verde",
			        "Rumipamba",
			        "San Antonio",
			        "San Blas",
			        "San Jacinto Del Bua",
			        "San Jose De Minas",
			        "San Marcos",
			        "San Miguel De Los Bancos",
			        "San Pedro De Taboada",
			        "San Rafael",
			        "San Roque",
			        "San Sebastian",
			        "Sangolqui",
			        "Sangolqui",
			        "Santa Barbara",
			        "Santa Prisca",
			        "Santa Rosa De Cuzubamba",
			        "Santo Domingo De Los Colorados",
			        "Santo Domingo De Los Colorados",
			        "Tababela",
			        "Tabacundo",
			        "Tambillo",
			        "Tocachi",
			        "Tumbaco",
			        "Tupigachi",
			        "Uyumbicho",
			        "Valle Hermoso",
			        "Villa Flora",
			        "Yaruqui",
			        "Zambiza",
			        "Zaracay"
			    ],
			],
		    [ 
		    	"name" => "Tungurahua",
		    	"cities" => [
			        "Ambatillo",
			        "Ambato",
			        "Atahualpa (Chisalata)",
			        "Atocha - Ficoa",
			        "Augusto N. Martinez (Mundugleo)",
			        "Baquerizo Moreno",
			        "Baños De Agua Santa",
			        "Benitez (Pachanlica)",
			        "Bolivar",
			        "Celiano Monge",
			        "Cevallos",
			        "Chiquicha",
			        "Ciudad Nueva",
			        "Constantino Fernandez",
			        "Cotalo",
			        "Cunchibamba",
			        "El Rosario (Rumichaca)",
			        "El Triunfo",
			        "Emilio Maria Teran (Rumipamba)",
			        "Garcia Moreno (Chumaqui)",
			        "Guambalo (Huambalo)",
			        "Huachi Chico",
			        "Huachi Grande",
			        "Huachi Loreto",
			        "Izamba",
			        "Juan Benigno Vela",
			        "La Matriz",
			        "La Merced",
			        "La Peninsula",
			        "Lligua",
			        "Los Andes",
			        "Marcos Espinel (Chacata)",
			        "Mocha",
			        "Montalvo",
			        "Pasa",
			        "Patate",
			        "Pelileo",
			        "Picaigua",
			        "Pilaguin (Pilahuin)",
			        "Pillaro",
			        "Pillaro",
			        "Pinguili",
			        "Pishilata",
			        "Presidente Urbina (Chagrapamba-Patzucul)",
			        "Quero",
			        "Quinchicoto",
			        "Quisapincha (Quizapincha)",
			        "Rio Negro",
			        "Rio Verde",
			        "Rumipamba",
			        "Salasaca",
			        "San Andres",
			        "San Bartolome De Pinllog",
			        "San Fernando (Pasa San Fernando)",
			        "San Francisco",
			        "San Jose De Poalo",
			        "San Miguelito",
			        "Santa Rosa",
			        "Sucre",
			        "Tisaleo",
			        "Totoras",
			        "Ulba",
			        "Unamuncho",
			        "Yanayacu - Mochapata"
		    	],
		    ],
		    [ 
		    	"name" => "Zamora Chinchipe",
		    	"cities" => [
			        "28 De Mayo (San Jose De Yacuambi)",
			        "Chicaña",
			        "Chito",
			        "Cumbaratza",
			        "El Chorro",
			        "El Guismi",
			        "El Pangui",
			        "El Porvenir Del Carmen",
			        "Guadalupe",
			        "Guayzimi",
			        "Imbana (La Victoria De Imbana)",
			        "La Chonta",
			        "La Paz",
			        "Limon",
			        "Los Encuentros",
			        "Pachicutza",
			        "Palanda",
			        "Paquisha",
			        "Pucapamba",
			        "Sabanilla",
			        "San Carlos De Las Minas",
			        "San Francisco De Vergel",
			        "Timbara",
			        "Tundayme",
			        "Tutupali",
			        "Valladolid",
			        "Yanzatza",
			        "Zamora",
			        "Zamora",
			        "Zumba",
			        "Zumbi",
			        "Zurmi"
			    ],
			],
		    [ 
		    	"name" => "Galapagos",
		    	"cities" => [
			        "Bellavista",
			        "El Progreso",
			        "Isla Santa Maria (Floreana)",
			        "Puerto Ayora",
			        "Puerto Baquerizo Moreno",
			        "Puerto Villamil",
			        "Santa Rosa",
			        "Tomas De Berlanga (Santo Tomas)"
			    ],
			],
		    [ 
		    	"name" => "Sucumbios",
		    	"cities" => [
			        "Aguas Negras",
			        "Cuyabeno",
			        "Dureno",
			        "El Dorado De Cascales",
			        "El Dorado De Cascales (Lumbaqui)",
			        "El Eno",
			        "El Playon De San Francisco",
			        "El Reventador",
			        "General Farfan",
			        "Gonzalo Pizarro",
			        "Jambeli",
			        "La Bonita",
			        "La Sofia",
			        "Limoncocha",
			        "Nueva Loja",
			        "Pacayacu",
			        "Palma Roja",
			        "Pañacocha",
			        "Puerto Bolivar (Puerto Montufar)",
			        "Puerto El Carmen Del Putumayo",
			        "Puerto Libre",
			        "Puerto Rodriguez",
			        "Rosa Florida",
			        "San Pedro De Los Cofanes",
			        "San Roque",
			        "Santa Barbara",
			        "Santa Cecilia",
			        "Santa Elena",
			        "Santa Rosa De Sucumbios",
			        "Sevilla",
			        "Shushufindi",
			        "Siete De Julio",
			        "Tarapoa"
			    ],
			],
		    [ 
		    	"name" => "Orellana",
			    "cities" => [
			        "Alejandro Labaca",
			        "Avila",
			        "Capitan Augusto Rivadeneira",
			        "Cononaco",
			        "Dayuma",
			        "El Dorado",
			        "El Eden",
			        "Enokanqui",
			        "Garcia Moreno",
			        "Ines Arango",
			        "La Belleza",
			        "La Joya De Los Sachas",
			        "Lago San Pedro",
			        "Loreto",
			        "Nuevo Paraiso",
			        "Nuevo Rocafuerte",
			        "Pompeya",
			        "Puerto Francisco De Orellana (Coca)",
			        "Puerto Murialdo",
			        "Rumipamba",
			        "San Carlos",
			        "San Jose De Dahuano",
			        "San Jose De Guayusa",
			        "San Jose Del Payamino",
			        "San Luis De Armenia",
			        "San Sebastian Del Coca",
			        "San Vicente De Huaticocha",
			        "Santa Maria De Huiririma",
			        "Taracoa",
			        "Tiputini",
			        "Tres De Noviembre",
			        "Union Milagreña",
			        "Yasuni"
			    ]
			],

		];

		$country = Country::create(['name'=>'Ecuador','shortname'=>'EC']);
		foreach ( $data as $province ) {
			$prov = Province::create(['name'=>$province['name'], 'country_id'=>$country->id]);
			foreach ($province['cities'] as $city) {
				City::create(['name'=>$city, 'province_id'=>$prov->id]);
			}
		}

	}

}
